---
title: "k_calcs_watertemp_data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, message=FALSE}
library(RPostgreSQL)
library(readr)
library(magrittr)
library(xts)
library(dplyr)
library(ggplot2)
library(readxl)
```

```{r dbconnect, include=FALSE}
password <- scan(".pgpass", what="")
db <- dbConnect(PostgreSQL(), 
                host = "sesync-postgis01.research.sesync.org",
                dbname = "choptank", 
                user = "palmergroup",
                password = password)
```

Water levels from 6 main sites between October and..
```{r}
ts <- read_excel("../wwl/data/inundation.xlsx", 
                 sheet="time_series", na = "-9999")
```

```{r}
tail(ts)
```


```{r}
wl_xts <- xts(ts$QB, order.by = ts$date)
# ep <- endpoints(qbMID_xts, on = "hour")
# temp_agg <- period.apply(qbMID_xts, INDEX = ep, FUN = mean)
```

```{r}
wl_df <- wl_xts %>%
  as.data.frame() %>%
  tibble::rownames_to_column(var = "date") %>%
  rename(wl_m = V1) %>%
  mutate(datetime = as.POSIXct(date))
```

```{r}
wl_xts %>%
  dygraph() %>%
  dyRangeSelector() %>%
  dyLegend() %>%
  dyOptions(strokeWidth = 1) %>%
  # dyHighlight(highlightSeriesOpts = list(strokeWidth = 3)) %>%
  dyOptions(useDataTimezone = TRUE) %>%
  dyRoller(rollPeriod = 5) %>% # plotted point represents average of specified number of timestamps
  dyAxis("y", label = "water level (m)")
```

```{r}
write_csv(wl_df, "data/waterlevel_qb.csv")
```

